export interface WorkbenchTable {
  date: string;
  start_time: string;
  end_time: string;
  unit: string;
  dept: string;
  project_code: string;
  tran_project_name: string;
  train_course_name: string;
  train_level: string;
  train_content: string;
  train_way1: string;
  train_way2: string;
  train_type: string;
  train_class: string;
  maintainer_id: number;
  train_place: string;
  trainer_id: number;
  trained_count_manage: number;
  trained_count_key: number;
  trained_count_product: number;
  trained_count_new: number;
  trained_count_work: number;
  trained_count_total: number;
  trained_hours_theory: number;
  trained_hours_pratice: number;
  trained_hours_total: number;
  train_effect_count: number;
  student_evaluation_score: number;
  maintainer_evaluation_score: number;
  effect_evaluation_score: number;
  course_pay: number;
  remark: string;
  // 主键
  id: number;
  // 是否已删除
  is_delete: number;
  // 创建时间
  created_time: string;
  createrName: string;
  createrCode: string;
  createrId: number;
}
