import { TeamGroupTable } from './TeamGroup';

export interface WorkbenchTable {
  // 1：计划培训，2：完成培训
  status: number;
  date: string;
  start_time: string;
  end_time: string;
  company: string;
  dept: string;
  group_id: number;
  group_name: TeamGroupTable['name'];
  group_type: TeamGroupTable['type'];
  project_code: string;
  train_project_name: string;
  train_course_name: string;
  train_level: string;
  train_content: string;
  train_way1: string;
  train_way2: string;
  train_type: string;
  train_class: string;
  maintainer: string;
  maintainer_code: string;
  train_place: string;
  trainer: string;
  trainer_code: string;
  // 0：无，1：见习，2：一星，3：二星，4：三星
  trainer_level: number;
  trainer_company: string;
  trained_count_manage: number;
  trained_count_key: number;
  trained_count_product: number;
  trained_count_new: number;
  trained_count_work: number;
  trained_count_total: number;
  trained_hours_theory: number;
  trained_hours_practice: number;
  trained_hours_total: number;
  train_effect_count: number;
  student_evaluation_score: number;
  maintainer_evaluation_score: number;
  effect_evaluation_score: number;
  course_pay: number;
  remark: string;
  // 主键
  id: number;
  // 是否已删除
  is_delete: number;
  // 创建时间
  created_time: string;
  creater_id: number;
}
